spring:
  application:
    name: product-service
  config:
    import:
     - 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ${CLOUD_SERVICE_ID}

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOSTNAME}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

rabbit:
  stock:
    exchange: stock.exchange
    registered:
      routing-key: stock.registered
      queue: stock.registered.queue